from typing import List, Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Request schema for financial document chat endpoint."""

    query: str = Field(
        ...,
        description="The financial query or question about the documents.",
        examples=["What was Tata Steel's EBITDA margin in FY2023-24?"],
    )
    dense_top_k: Optional[int] = Field(
        default=None,
        ge=1,
        description="Optional number of semantic candidates from FAISS.",
    )
    sparse_top_k: Optional[int] = Field(
        default=None,
        ge=1,
        description="Optional number of lexical candidates from BM25.",
    )
    final_top_k: Optional[int] = Field(
        default=None,
        ge=1,
        description="Optional number of top reranked chunks in the final context.",
    )


class SourceItem(BaseModel):
    """Source citation metadata for retrieved financial chunks."""

    source: str = Field(
        ...,
        description="Name of the source document file.",
        examples=["OTC_TATLY_2024.pdf"],
    )
    page: int = Field(
        ...,
        description="Page number in the source document.",
        examples=[14],
    )
    chunk_id: str = Field(
        ...,
        description="Deterministic stable identity of the chunk.",
        examples=["OTC_TATLY_2024.pdf::page_14::chunk_3::c6a111a9b067"],
    )
    rerank_score: Optional[float] = Field(
        default=None,
        description="Cross-Encoder relevance score.",
    )
    rrf_score: Optional[float] = Field(
        default=None,
        description="Reciprocal Rank Fusion score before reranking.",
    )


class ChatMetrics(BaseModel):
    """Execution performance metrics for the request."""

    retrieval_candidates: int = Field(
        ...,
        description="Number of candidate chunks retrieved before reranking.",
    )
    reranked_chunks: int = Field(
        ...,
        description="Number of top chunks passed to the LLM context.",
    )
    latency_seconds: float = Field(
        ...,
        description="Total request latency in seconds.",
    )


class ChatResponse(BaseModel):
    """Response schema for financial document chat endpoint."""

    query: str = Field(
        ...,
        description="The original user query.",
    )
    answer: str = Field(
        ...,
        description="Grounded response generated by the local LLM.",
    )
    sources: List[SourceItem] = Field(
        default_factory=list,
        description="List of source citations supporting the answer.",
    )
    metrics: ChatMetrics = Field(
        ...,
        description="Pipeline performance and latency metrics.",
    )
